### ISSUE TITLE
standar work todo

### ISSUE THREAD

**Issue by JanezCim** [UbiquityRobotics/breadcrumb_learn#21]
- [x] add page number
- [x] cables make all in one place?
- [x] iz vrečke screen zašraufaj ta šrauf tja pa tja
- [x] popravi število šravforv zarad sestavljenega zaslona
- [x] odstrani šraufe iz vrečk ce se bojo monteral front paneeli in chanrging paneli 
- [x] dodaj sraufe za side cover
